controller_list:
  - name: right_arm_position_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - Arm_R1_joint
      - Arm_R2_joint
      - Arm_R3_joint
      - Arm_R4_joint
      - Arm_R5_joint
      - Arm_R6_joint

  - name: left_arm_position_joint_trajectory_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - Arm_L1_joint
      - Arm_L2_joint
      - Arm_L3_joint
      - Arm_L4_joint
      - Arm_L5_joint
      - Arm_L6_joint

  - name: gripper_controller
    action_ns: gripper_action
    type: GripperCommand
    default: true
    joints:
      - finger_joint

 - name: tool_controller
    joints:
      []
  
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    allowed_execution_duration_scaling: 1.2
    allowed_goal_duration_margin: 0.5
