right_arm:
  # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin # default
  kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin # LMA (Levenberg-Marquardt) 
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005

left_arm:
  # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin # default
  kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin # LMA (Levenberg-Marquardt) 
  kinematics_solver_search_resolution: 0.005
  kinematics_solver_timeout: 0.005
