right_arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin # sudo apt-get install ros-melodic-trac-ik-kinematics-plugin
  kinematics_solver_timeout: 0.005
  solve_type: Speed  # Speed, Distance, Manipulation1, Manipulation2

left_arm:
  kinematics_solver: trac_ik_kinematics_plugin/TRAC_IKKinematicsPlugin # sudo apt-get install ros-melodic-trac-ik
  kinematics_solver_timeout: 0.005
  solve_type: Speed  # Speed, Distance, Manipulation1, Manipulation2



# right_arm:
#   # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin # default
#   kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin # LMA (Levenberg-Marquardt) 
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005

# left_arm:
#   # kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin # default
#   kinematics_solver: lma_kinematics_plugin/LMAKinematicsPlugin # LMA (Levenberg-Marquardt) 
#   kinematics_solver_search_resolution: 0.005
#   kinematics_solver_timeout: 0.005


