# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: right_arm
  joint_model_group_pose: work
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - Arm_L1_joint
    - Arm_L2_joint
    - Arm_L3_joint
    - Arm_L4_joint
    - Arm_L5_joint
    - Arm_L6_joint
    - Arm_R1_joint
    - Arm_R2_joint
    - Arm_R3_joint
    - Arm_R4_joint
    - Arm_R5_joint
    - Arm_R6_joint
    - finger_joint
    - left_back_wheel_joint
    - right_back_wheel_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  []
left_arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - Arm_L1_joint
    - Arm_L2_joint
    - Arm_L3_joint
    - Arm_L4_joint
    - Arm_L5_joint
    - Arm_L6_joint
  gains:
    Arm_L1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Arm_L2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Arm_L3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Arm_L4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Arm_L5_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Arm_L6_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
right_arm_position_controller:
  type: position_controllers/JointPositionController
  joints:
    - Arm_R1_joint
    - Arm_R2_joint
    - Arm_R3_joint
    - Arm_R4_joint
    - Arm_R5_joint
    - Arm_R6_joint
  gains:
    Arm_R1_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Arm_R2_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Arm_R3_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Arm_R4_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Arm_R5_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
    Arm_R6_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1
gripper_position_controller:
  type: position_controllers/JointTrajectoryController
  joints:
    finger_joint
  gains:
    finger_joint:
      p: 100
      d: 1
      i: 1
      i_clamp: 1