# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: right_arm
  joint_model_group_pose: arm_right_work
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - Arm_L1_joint
    - Arm_L2_joint
    - Arm_L3_joint
    - Arm_L4_joint
    - Arm_L5_joint
    - Arm_L6_joint
    - Arm_R1_joint
    - Arm_R2_joint
    - Arm_R3_joint
    - Arm_R4_joint
    - Arm_R5_joint
    - Arm_R6_joint
    - gripper_finger1_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50
controller_list:
  - name: right_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - Arm_R1_joint
      - Arm_R2_joint
      - Arm_R3_joint
      - Arm_R4_joint
      - Arm_R5_joint
      - Arm_R6_joint
  - name: left_arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - Arm_L1_joint
      - Arm_L2_joint
      - Arm_L3_joint
      - Arm_L4_joint
      - Arm_L5_joint
      - Arm_L6_joint