<?xml version="1.0" encoding="utf-8"?>

<robot name="eod_robot_description_vehicle" xmlns:xacro="http://www.ros.org/wiki/xacro">


<xacro:property name="wheel_x_front" value="-0.062"/>
<xacro:property name="wheel_x_back" value="-0.602"/>
<xacro:property name="wheel_z" value="-0.402"/>
<xacro:property name="wheel_y" value="0.2765"/>
<xacro:property name="Radius" value="0.108"/>
<xacro:property name="casterMass" value="2"/>
<xacro:property name="wheel_m" value="2"/>
<xacro:property name="wheel_l" value="0.06"/>


<xacro:macro name="vehicle">

    <link name="caster_wheel_link">
        <collision>
            <origin xyz="${wheel_x_front} 0 ${wheel_z}" rpy="0 0 0"/>
            <geometry>
            <sphere radius="${Radius}"/>
            </geometry>
        </collision>
        
        <visual>
            <origin xyz="${wheel_x_front} 0 ${wheel_z}" rpy="0 0 0"/>
            <geometry>
            <sphere radius="${Radius}"/>
            </geometry>
            <material name="">  
                <color rgba="0 0.5 0.8  0"/>  
            </material>  
        </visual>

        <inertial>
            <origin xyz="${wheel_x_front} 0 ${wheel_z}" rpy="0 0 0"/>
            <mass value="${casterMass}"/>
            <inertia ixx="${2/5*casterMass*Radius*Radius}" ixy= "0" ixz= "0"
                iyy="${2/5*casterMass*Radius*Radius}" iyz= "0"
                izz="${2/5*casterMass*Radius*Radius}" /> 
        </inertial>
    </link>

    <joint name="caster_wheel_fixed" type="fixed">
        <parent link="base_link"/>
        <child link="caster_wheel_link"/>
    </joint>


    <link name="right_back_wheel">  
      <visual>  
          <geometry>  
            <cylinder length="${wheel_l}" radius="${Radius}"/>  
          </geometry>  
          <origin xyz="0 ${wheel_l/2} 0" rpy="1.5708 0 0" />
          <material name="">  
            <color rgba="0 0.5 0.8 1"/>  
          </material>  
      </visual>  
        <inertial>
            <mass value="${wheel_m}" />
            <inertia ixx="${wheel_m/12*(3*Radius*Radius + wheel_l*wheel_l)}" ixy= "0" ixz= "0"
                iyy="${wheel_m/2*Radius*Radius}" iyz= "0"
                izz="${wheel_m/12*(3*Radius*Radius + wheel_l*wheel_l)}" /> 
        </inertial>  
        <collision>
          <origin xyz="0 ${-wheel_l/2} 0" rpy="1.5708 0 0" />
          <geometry>
            <cylinder length="${wheel_l}" radius="${Radius}"/>
          </geometry>
        </collision>   
    </link>  
    
    <joint name="right_back_wheel_joint" type="continuous">  
        <axis xyz="0 1 0"/>  
        <parent link="base_link"/>  
        <child link="right_back_wheel"/>  
        <origin rpy="0 0 0" xyz="${wheel_x_back} ${-wheel_y} ${wheel_z}"/>  
        <limit effort="100" velocity="100"/>  
        <joint_properties damping="0.0" friction="0.0"/>  
    </joint>  

    
    <link name="left_back_wheel">  
        <visual>  
            <geometry>  
                <cylinder length="${wheel_l}" radius="${Radius}"/>   
            </geometry>  
            <origin xyz="0 ${-wheel_l/2} 0" rpy="1.5708 0 0" />
            <material name="">  
                <color rgba="0 0.5 0.8 1"/>  
            </material>  
        </visual> 
        <inertial>
            <mass value="${wheel_m}" />
            <inertia ixx="${wheel_m/12*(3*Radius*Radius + wheel_l*wheel_l)}" ixy= "0" ixz= "0"
                iyy="${wheel_m/2*Radius*Radius}" iyz= "0"
                izz="${wheel_m/12*(3*Radius*Radius + wheel_l*wheel_l)}" /> 
        </inertial> 
        <collision>
          <origin xyz="0 ${-wheel_l/2} 0" rpy="1.5708 0 0" />
          <geometry>
            <cylinder length="${wheel_l}" radius="${Radius}"/>  
          </geometry>
        </collision>       
    </link>  
    
    <joint name="left_back_wheel_joint" type="continuous">  
        <axis xyz="0 1 0"/>  
        <parent link="base_link"/>  
        <child link="left_back_wheel"/>  
        <origin rpy="0 0 0" xyz="${wheel_x_back} ${wheel_y} ${wheel_z}"/>  
        <limit effort="100" velocity="100"/>  
        <joint_properties damping="0.0" friction="0.0"/>  
    </joint>  

  <link
    name="base_link">
    <inertial>
      <origin xyz="-0.17885 0.0017998 -0.1738" rpy="0 0 0" />
      <mass value="107.28" />
      <inertia ixx="1.52" ixy="0.001111" ixz="0.079409" iyy="2.3271" iyz="-0.00027816" izz="3.0127" />
    </inertial>
    <visual>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://eod_robot_description/meshes/base_link.STL" />
      </geometry>
      <material name="">
        <color rgba="0.0078 0.4686 0.2294 1" />
      </material>
    </visual>
    <collision>
      <origin xyz="0 0 0" rpy="0 0 0" />
      <geometry>
        <mesh filename="package://eod_robot_description/meshes/base_link.STL" />
      </geometry>
    </collision>
  </link>    

    <transmission name="right_back_wheel_joint_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="right_back_wheel_joint" >
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="right_back_wheel_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>

    <transmission name="left_back_wheel_joint_trans">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="left_back_wheel_joint" >
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="left_back_wheel_joint_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>


 <gazebo>
  <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
    <robotNamespace>/eod_robot_description</robotNamespace>
    <alwaysOn>true</alwaysOn>
    <legacyMode>false</legacyMode>
    <updateRate>50</updateRate>
    <leftJoint>left_back_wheel_joint</leftJoint>
    <rightJoint>right_back_wheel_joint</rightJoint>
    <wheelSeparation>${2*wheel_y - wheel_l}</wheelSeparation>
    <wheelDiameter>${2*Radius}</wheelDiameter>
    <wheelAcceleration>1.0</wheelAcceleration>
    <torque>50</torque>
    <commandTopic>cmd_vel</commandTopic>
    <odometryTopic>odom</odometryTopic>
    <odometryFrame>odom</odometryFrame>
    <robotBaseFrame>base_link</robotBaseFrame>
    <publishOdom>true</publishOdom>
  </plugin>
</gazebo>

<gazebo reference="caster_wheel_link">
  <mu1>0.0</mu1>
  <mu2>0.0</mu2>
  <material>Gazebo/GreenTransparent</material>
</gazebo>

  <gazebo reference="right_back_wheel">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>10000000</kp>
    <kd>1.0</kd>  
    <fdir1 value="1 0 0"/>   
    <material>Gazebo/GreenTransparent</material>      
  </gazebo>

  <gazebo reference="left_back_wheel">
    <mu1>1.0</mu1>
    <mu2>1.0</mu2>
    <kp>10000000</kp>
    <kd>1.0</kd>  
    <fdir1 value="1 0 0"/>   
    <material>Gazebo/GreenTransparent</material>    
  </gazebo>

<gazebo reference="base_link">
    <implicitSpringDamper>1</implicitSpringDamper>
    <mu1>100000</mu1>
    <mu2>100000</mu2>
    <kp>100000000.0</kp>
    <kd>1.0</kd>
    <material>Gazebo/Green</material>
  </gazebo>

<gazebo reference="counter_weight_link">
    <implicitSpringDamper>1</implicitSpringDamper>
    <mu1>100000</mu1>
    <mu2>100000</mu2>
    <kp>100000000.0</kp>
    <kd>1.0</kd>
    <material>Gazebo/GreenTransparent</material>
  </gazebo>

</xacro:macro>

</robot>
