eod_robot_description:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

 # Effort Controllers ---------------------------------------  
  right_back_effort_controller:
    type: effort_controllers/JointEffortController
    joint: right_back_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  left_back_effort_controller:
    type: effort_controllers/JointEffortController
    joint: left_back_wheel_joint
    pid: {p: 100.0, i: 0.01, d: 10.0}
  
  # Position Controllers ---------------------------------------
  Arm_R1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_R1_joint
    pid: {p: 180.0, i: 60, d: 15.0}
  Arm_R2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_R2_joint
    pid: {p: 180.0, i: 60, d: 15.0}
  Arm_R3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_R3_joint
    pid: {p: 180.0, i: 60, d: 15.0}
  Arm_R4_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_R4_joint
    pid: {p: 50.0, i: 1, d: 10.0}
  Arm_R5_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_R5_joint
    pid: {p: 25.0, i: 0.1, d: 2.5}
  Arm_R6_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_R6_joint
    pid: {p: 5.0, i: 0.05, d: 0.1}

  Arm_L1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_L1_joint
    pid: {p: 100.0, i: 1, d: 10.0}
  Arm_L2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_L2_joint
    pid: {p: 100.0, i: 1, d: 10.0}
  Arm_L3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_L3_joint
    pid: {p: 100.0, i: 1, d: 10.0}
  Arm_L4_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_L4_joint
    pid: {p: 50.0, i: 1, d: 5.0}
  Arm_L5_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_L5_joint
    pid: {p: 25.0, i: 0.1, d: 2.5}
  Arm_L6_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_L6_joint
    pid: {p: 5.0, i: 0.05, d: 0.1}
  
  Gripper_finger1_joint_position_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      # - gripper_finger1_joint
      - finger_joint
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        gripper_finger1_joint: {trajectory: 0.1, goal: 0.2}   
    stop_trajectory_duration: 0.5
    state_publish_rate:  50
    action_monitor_rate: 10

    # robotiq
  gazebo_ros_control:
    pid_gains:
      # these gains are used by the gazebo_ros_control plugin
      finger_joint:
        p: 10.0
        i: 0.5
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true
      # the following gains are used by the gazebo_mimic_joint plugin
      left_inner_knuckle_joint:
        p: 10.0
        i: 0.5
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true

      left_inner_finger_joint:
        p: 10.0
        i: 0.5
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true

      right_outer_knuckle_joint:
        p: 10.0
        i: 0.5
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true

      right_inner_knuckle_joint:
        p: 10.0
        i: 0.5
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true

      right_inner_finger_joint:
        p: 10.0
        i: 0.1
        d: 0.0
        i_clamp: 0.2
        antiwindup: false
        publish_state: true


    # gripper  
  # gazebo_ros_control:
  #   pid_gains:
  #     gripper_finger1_joint:
  #       p: 10.0
  #       i: 0.1
  #       d: 0.0
  #       i_clamp: 0.2
  #       antiwindup: false
  #       publish_state: true

  #     gripper_finger2_joint:
  #       p: 0.1
  #       i: 0.1
  #       d: 0.0
  #       i_clamp: 0.2
  #       antiwindup: false
  #       publish_state: true

  #     gripper_finger2_inner_knuckle_joint:
  #       p: 10.0
  #       i: 0.1
  #       d: 0.0
  #       i_clamp: 0.2
  #       antiwindup: false
  #       publish_state: true

  #     gripper_finger1_inner_knuckle_joint:
  #       p: 10.0
  #       i: 0.1
  #       d: 0.0
  #       i_clamp: 0.2
  #       antiwindup: false
  #       publish_state: true

  #     gripper_finger1_finger_tip_joint:
  #       p: 10.0
  #       i: 0.1
  #       d: 0.0
  #       i_clamp: 0.2
  #       antiwindup: false
  #       publish_state: true

  #     gripper_finger2_finger_tip_joint:
  #       p: 10.0
  #       i: 0.1
  #       d: 0.0
  #       i_clamp: 0.2
  #       antiwindup: false
  #       publish_state: true

  #     gripper_finger1_finger_joint:
  #       p: 10.0
  #       i: 0.1
  #       d: 0.0
  #       i_clamp: 0.2
  #       antiwindup: false
  #       publish_state: true

  #     gripper_finger2_finger_joint:
  #       p: 10.0
  #       i: 0.1
  #       d: 0.0
  #       i_clamp: 0.2
  #       antiwindup: false
  #       publish_state: true




 