eod_robot_description:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  Arm_R1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_R1_joint
    pid: {p: 180.0, i: 60, d: 15.0}
  Arm_R2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_R2_joint
    pid: {p: 180.0, i: 60, d: 15.0}
  Arm_R3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_R3_joint
    pid: {p: 180.0, i: 60, d: 15.0}
  Arm_R4_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_R4_joint
    pid: {p: 50.0, i: 1, d: 10.0}
  Arm_R5_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_R5_joint
    pid: {p: 25.0, i: 0.1, d: 2.5}
  Arm_R6_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_R6_joint
    pid: {p: 5.0, i: 0.05, d: 0.1}

  Arm_L1_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_L1_joint
    pid: {p: 100.0, i: 1, d: 10.0}
  Arm_L2_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_L2_joint
    pid: {p: 100.0, i: 1, d: 10.0}
  Arm_L3_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_L3_joint
    pid: {p: 100.0, i: 1, d: 10.0}
  Arm_L4_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_L4_joint
    pid: {p: 50.0, i: 1, d: 5.0}
  Arm_L5_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_L5_joint
    pid: {p: 25.0, i: 0.1, d: 2.5}
  Arm_L6_joint_position_controller:
    type: effort_controllers/JointPositionController
    joint: Arm_L6_joint
    pid: {p: 5.0, i: 0.05, d: 0.1}
  
  Gripper_finger1_joint_position_controller:
    type: position_controllers/JointTrajectoryController
    joints:
      - gripper_finger1_joint
    pid_gains: 
      gripper_finger1_joint: {p: 100,  d: 1, i: 1, i_clamp: 1}
    constraints:
        goal_time: 0.6
        stopped_velocity_tolerance: 0.05
        gripper_finger1_joint: {trajectory: 0.1, goal: 0.0}
    stop_trajectory_duration: 0.5
    state_publish_rate:  50
    action_monitor_rate: 10

 